import fs from "node:fs";
import { Window } from "happy-dom";

// @ts-ignore this sets a browser-like environment in Node.js
globalThis.window = new Window();
globalThis.document = window.document;

async function main() {
  await import("../src/index.ts");

  const content = [
    "<!DOCTYPE html>",
    "<!--",
    "This file is generated by the build script.",
    "Do not edit it directly.",
    "-->",
    document.documentElement.outerHTML,
  ].join("\n");

  fs.writeFileSync("docs/index.html", content, "utf-8");
}

main();
