import "./browser-globals.ts";
import "../src/index.ts";
import fs from "node:fs";

const content = [
  "<!DOCTYPE html>",
  "<!--",
  "This file is generated by the build script.",
  "Do not edit it directly.",
  "-->",
  document.documentElement.outerHTML,
].join("\n");

fs.writeFileSync("docs/index.html", content, "utf-8");
